import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import type { CSSProperties } from "react";
import { getAgentImage } from "./mediaFallbacks";
import { fineTuneAttributes, themeStyleVariables, type SiteTemplateProps } from "./types";
import { SharedFooterContact } from "./SharedFooterContact";

export function SharedTeamHeaderLink({ config }: SiteTemplateProps) {
  if (!config.showTeamSection || !config.teamMembers.length) return null;
  const href = config.view === "home" ? "#ekibimiz" : `/site/${config.slug}#ekibimiz`;
  return <a href={href}>{config.teamSectionLabel}</a>;
}

export function SharedTeamSection({ config, force = false }: SiteTemplateProps & { force?: boolean }) {
  if (!config.showTeamSection || !config.teamMembers.length || (!force && config.view !== "home")) return null;
  return <section id="ekibimiz" data-team-section className="border-y border-current/10 px-5 py-20 sm:px-8 lg:px-10" style={{ background: `color-mix(in srgb, ${config.colors.accent} 8%, ${config.colors.background})`, color: config.colors.text }}><div className="mx-auto max-w-[1400px]"><div className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: config.colors.accent }}>{config.content.eyebrow}</div><h2 className="mt-4 text-5xl font-bold" style={{ fontFamily: config.fonts.heading }}>{config.teamSectionLabel}</h2><p className="mt-4 max-w-2xl leading-7 opacity-65">{config.content.teamDescription}</p><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{config.teamMembers.map((member, index) => <article key={member.id} data-team-member className="overflow-hidden border border-current/10" style={{ background: config.colors.background }}><img src={getAgentImage(`${config.siteId}-${member.id}-${index}`, member.photo_url)} alt={member.name} className="aspect-[4/3] w-full object-cover" /><div className="p-6"><h3 className="text-3xl font-bold" style={{ fontFamily: config.fonts.heading }}>{member.name}</h3><div className="mt-2 text-xs font-bold uppercase tracking-wider" style={{ color: config.colors.accent }}>{member.role}</div>{member.bio ? <p className="mt-4 text-sm leading-7 opacity-65">{member.bio}</p> : null}</div></article>)}</div>{config.templateId === "land-plots" && config.content.processSteps.length ? <div className="mt-20 border-t border-current/10 pt-16"><h3 className="text-4xl font-bold" style={{ fontFamily: config.fonts.heading }}>{config.content.processTitle}</h3><div className="mt-9 grid gap-6 md:grid-cols-3">{config.content.processSteps.map((step, index) => <article key={`${step.title}-${index}`} className="border-t border-current/15 pt-5"><div className="text-sm font-bold" style={{ color: config.colors.accent }}>{String(index + 1).padStart(2, "0")}</div><h4 className="mt-3 text-2xl font-bold" style={{ fontFamily: config.fonts.heading }}>{step.title}</h4><p className="mt-3 text-sm leading-7 opacity-65">{step.description}</p></article>)}</div></div> : null}</div></section>;
}

export function SharedTeamPage({ config }: SiteTemplateProps) {
  const c = config.content;
  const style = { ...themeStyleVariables(config), backgroundColor: config.colors.background, color: config.colors.text, fontFamily: config.fonts.body } as CSSProperties;
  return <div {...fineTuneAttributes(config)} style={style}><header className="border-b border-current/10"><div className="mx-auto flex h-20 max-w-[1400px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link to={`/site/${config.slug}`} className="text-2xl font-bold" style={{ fontFamily: config.fonts.heading }}>{c.businessName}</Link><Link to={`/site/${config.slug}`} className="inline-flex items-center gap-2 text-xs font-bold"><ArrowLeft className="h-4 w-4" />{c.backLabel}</Link></div></header><main><section className="px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1400px]"><div className="text-xs font-bold uppercase tracking-[.2em]" style={{ color: config.colors.accent }}>{c.eyebrow}</div><h1 className="mt-4 text-6xl font-bold" style={{ fontFamily: config.fonts.heading }}>{config.teamSectionLabel}</h1><p className="mt-4 max-w-2xl leading-7 opacity-65">{c.teamDescription}</p><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{config.teamMembers.map((member, index) => <article key={member.id} data-team-member className="overflow-hidden border border-current/10"><img src={getAgentImage(`${config.siteId}-${member.id}-${index}`, member.photo_url)} alt={member.name} className="aspect-[4/3] w-full object-cover" /><div className="p-6"><h2 className="text-3xl font-bold" style={{ fontFamily: config.fonts.heading }}>{member.name}</h2><div className="mt-2 text-xs font-bold uppercase tracking-wider" style={{ color: config.colors.accent }}>{member.role}</div>{member.bio ? <p className="mt-4 text-sm leading-7 opacity-65">{member.bio}</p> : null}</div></article>)}</div></div></section>{config.templateId === "land-plots" && c.processSteps.length ? <section className="border-y border-current/10 px-5 py-20 sm:px-8 lg:px-10" style={{ background: `color-mix(in srgb, ${config.colors.accent} 9%, ${config.colors.background})` }}><div className="mx-auto max-w-[1400px]"><h2 className="text-5xl font-bold" style={{ fontFamily: config.fonts.heading }}>{c.processTitle}</h2><div className="mt-10 grid gap-6 md:grid-cols-3">{c.processSteps.map((step, index) => <article key={`${step.title}-${index}`} className="border-t border-current/15 pt-6"><div className="text-sm font-bold" style={{ color: config.colors.accent }}>{String(index + 1).padStart(2, "0")}</div><h3 className="mt-4 text-3xl font-bold" style={{ fontFamily: config.fonts.heading }}>{step.title}</h3><p className="mt-3 text-sm leading-7 opacity-60">{step.description}</p></article>)}</div></div></section> : null}</main><footer className="px-5 py-12 text-white sm:px-8 lg:px-10" style={{ background: config.colors.primary }}><div className="mx-auto max-w-[1400px]"><div><div className="text-xl font-bold" style={{ fontFamily: config.fonts.heading }}>{c.businessName}</div><p className="mt-2 text-sm opacity-65">{c.tagline}</p></div></div><SharedFooterContact config={config} /></footer></div>;
}
