import { useMemo, useState, type CSSProperties, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, MapPin, X } from "lucide-react";
import type { Listing } from "@/portfoyai/types";
import { formatListingPrice } from "@/lib/listing-price";
import { formatListingLocation } from "@/portfoyai/listing-location";
import { SharedTeamFooterLink, SharedTeamSection } from "../SharedTeamPage";
import { ClosedListingsGroups } from "../ClosedListingsGroups";
import { getListingImage } from "../mediaFallbacks";
import { propertySubtypeFor, propertyTaxonomyLabel } from "../PropertyTaxonomy";
import { fineTuneAttributes, themeStyleVariables, type SiteTemplateProps, type TemplateConfig } from "../types";

const landStyle = (config: TemplateConfig) => ({
  ...themeStyleVariables(config),
  "--lp-bg": config.colors.background,
  "--lp-primary": config.colors.primary,
  "--lp-accent": config.colors.accent,
  "--lp-text": config.colors.text,
  "--lp-soft": `color-mix(in srgb, ${config.colors.accent} 9%, ${config.colors.background})`,
  "--lp-line": `color-mix(in srgb, ${config.colors.text} 14%, transparent)`,
  "--lp-heading": config.fonts.heading,
  "--lp-body": config.fonts.body,
  backgroundColor: "var(--lp-bg)", color: "var(--lp-text)", fontFamily: "var(--lp-body)",
}) as CSSProperties;

function Header({ config }: SiteTemplateProps) {
  const c = config.content;
  return <header className="border-b border-[var(--lp-line)] bg-[var(--lp-bg)]"><div className="mx-auto flex h-20 max-w-[1400px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link to={`/site/${config.slug}`} className="font-[family-name:var(--lp-heading)] text-2xl font-bold">{c.businessName}</Link><nav className="hidden items-center gap-8 text-xs font-semibold md:flex"><a href={`/site/${config.slug}#hizmetler`}>{c.navAbout}</a><Link to={`/site/${config.slug}/listings`}>{c.navListings}</Link><a href="#iletisim">{c.navContact}</a></nav><Link data-site-button to={`/site/${config.slug}/listings`} className="bg-[var(--site-button)] px-5 py-3 text-xs font-bold text-[var(--site-button-text)]">{c.ctaText}</Link></div></header>;
}

function Footer({ config }: SiteTemplateProps) {
  const c = config.content;
  return <><SharedTeamSection config={config} /><footer id="iletisim" className="bg-[var(--lp-primary)] px-5 py-14 text-white sm:px-8 lg:px-10"><div className="mx-auto grid max-w-[1400px] gap-10 md:grid-cols-[1fr_auto_auto]"><div><div className="font-[family-name:var(--lp-heading)] text-3xl font-bold">{c.businessName}</div><p className="mt-3 max-w-md text-sm leading-7 opacity-65">{c.tagline}</p><div className="mt-5 text-xs opacity-40">Fastate AI ile hazırlandı</div></div><nav className="space-y-3 text-sm opacity-75"><Link className="block" to={`/site/${config.slug}/listings`}>{c.navListings}</Link><a className="block" href={`/site/${config.slug}#hizmetler`}>{c.navAbout}</a></nav><address className="space-y-2 text-sm not-italic opacity-75"><div>{c.address}</div><div>{c.phone}</div><div>{c.email}</div></address></div><SharedTeamFooterLink config={config} /></footer></>;
}

function FeatureList({ listing, compact = false }: { listing: Listing; compact?: boolean }) {
  return <div className={compact ? "mt-4 space-y-2" : "grid gap-3 sm:grid-cols-2"}>{listing.features.slice(0, compact ? 3 : undefined).map((feature) => <div key={feature} className="flex items-center gap-2 text-sm"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[var(--lp-soft)] text-[var(--lp-accent)]"><Check className="h-3 w-3" /></span>{feature}</div>)}</div>;
}

function LandCard({ config, listing }: { config: TemplateConfig; listing: Listing }) {
  const c = config.content;
  return <article className="overflow-hidden border border-[var(--lp-line)] bg-[var(--lp-bg)]"><Link to={`/site/${config.slug}/listings/${listing.id}`} className="relative block overflow-hidden"><img src={getListingImage(listing)} alt={listing.title} className="aspect-[4/3] w-full object-cover transition duration-500 hover:scale-[1.025]" /><span className="absolute left-4 top-4 bg-[var(--lp-primary)] px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-white">{propertyTaxonomyLabel(config, listing)}</span></Link><div className="p-6"><div className="flex items-center gap-2 text-xs text-[var(--lp-accent)]"><MapPin className="h-4 w-4" />{formatListingLocation(listing)}</div><Link to={`/site/${config.slug}/listings/${listing.id}`}><h3 className="mt-3 font-[family-name:var(--lp-heading)] text-2xl font-bold leading-tight">{listing.title}</h3></Link><div className="mt-5 flex items-end justify-between border-t border-[var(--lp-line)] pt-4"><strong className="text-lg">{formatListingPrice(listing)}</strong><span className="text-sm opacity-60">{listing.m2} m²</span></div><FeatureList listing={listing} compact /><Link className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[var(--lp-accent)]" to={`/site/${config.slug}/listings/${listing.id}`}>{c.detailsLabel}<ArrowRight className="h-4 w-4" /></Link></div></article>;
}

function LeadDialog({ config, listing, open, onClose }: { config: TemplateConfig; listing: Listing; open: boolean; onClose: () => void }) {
  const c = config.content;
  const [form, setForm] = useState({ name: "", phone: "", message: "" });
  const [status, setStatus] = useState<"idle" | "submitting" | "success" | "error">("idle");
  if (!open) return null;
  const submit = async (event: FormEvent) => { event.preventDefault(); setStatus("submitting"); try { const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ site_id: config.siteId, listing_id: listing.id, ...form }) }); if (!response.ok) throw new Error(); setStatus("success"); } catch { setStatus("error"); } };
  const field = "w-full border border-[var(--lp-line)] bg-white px-4 py-3 text-sm outline-none focus:border-[var(--lp-accent)]";
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/55 p-5" role="dialog" aria-modal="true"><div className="relative w-full max-w-md bg-[var(--lp-bg)] p-7 shadow-2xl"><button onClick={onClose} aria-label={c.backLabel} className="absolute right-4 top-4"><X className="h-5 w-5" /></button><h2 className="font-[family-name:var(--lp-heading)] text-3xl font-bold">{c.tourTitle}</h2><p className="mt-3 text-sm leading-6 opacity-60">{c.tourDescription}</p><form onSubmit={submit} className="mt-6 space-y-3"><input className={field} placeholder={c.fullNameLabel} required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className={field} placeholder={c.phoneLabel} required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><textarea className={`${field} min-h-24`} placeholder={c.messageLabel} value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /><button data-site-button className="w-full bg-[var(--site-button)] px-5 py-3 text-sm font-bold text-[var(--site-button-text)]">{status === "submitting" ? c.formSubmitting : c.formSubmit}</button>{status === "success" ? <p className="text-sm text-[var(--lp-accent)]">{c.formSuccess}</p> : null}{status === "error" ? <p className="text-sm">{c.formError}</p> : null}</form></div></div>;
}

export function LandPlotsHome({ config }: SiteTemplateProps) {
  const c = config.content;
  const hero = config.listings[0] ? getListingImage(config.listings[0]) : "";
  return <div {...fineTuneAttributes(config)} style={landStyle(config)}><Header config={config} /><main><section className="relative min-h-[680px] bg-[var(--lp-primary)] text-white"><img src={hero} alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,color-mix(in_srgb,var(--lp-primary)_90%,transparent),color-mix(in_srgb,var(--lp-primary)_30%,transparent))]" /><div className="relative mx-auto flex min-h-[680px] max-w-[1400px] items-center px-5 py-24 sm:px-8 lg:px-10"><div className="max-w-3xl"><div className="text-xs font-bold uppercase tracking-[0.24em] text-[var(--lp-accent)]">{c.eyebrow}</div><h1 className="mt-6 font-[family-name:var(--lp-heading)] text-6xl font-bold leading-[.94] sm:text-7xl">{c.headline}<span className="mt-2 block font-normal italic">{c.headlineAccent}</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-white/75">{c.bio}</p><div className="mt-9 flex flex-wrap gap-3"><Link data-site-button className="bg-[var(--site-button)] px-6 py-4 text-sm font-bold text-[var(--site-button-text)]" to={`/site/${config.slug}/listings`}>{c.ctaText}</Link><a data-site-button className="border border-white/60 px-6 py-4 text-sm font-bold" href="#iletisim">{c.navContact}</a></div></div></div></section><section id="hizmetler" className="px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1400px]"><div className="max-w-2xl"><div className="text-xs font-bold uppercase tracking-[.2em] text-[var(--lp-accent)]">{c.navAbout}</div><h2 className="mt-4 font-[family-name:var(--lp-heading)] text-5xl font-bold">{c.servicesTitle}</h2><p className="mt-4 leading-7 opacity-60">{c.servicesDescription}</p></div><div className="mt-12 grid border-l border-t border-[var(--lp-line)] md:grid-cols-2 lg:grid-cols-4">{c.services.map((service) => <article key={service.title} className="border-b border-r border-[var(--lp-line)] p-7"><h3 className="font-[family-name:var(--lp-heading)] text-2xl font-bold">{service.title}</h3><p className="mt-4 text-sm leading-7 opacity-60">{service.description}</p></article>)}</div></div></section><section className="bg-[var(--lp-soft)] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1400px]"><div className="flex items-end justify-between gap-5"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-[var(--lp-accent)]">{c.featuredEyebrow}</div><h2 className="mt-4 font-[family-name:var(--lp-heading)] text-5xl font-bold">{c.featuredTitle}</h2></div><Link className="hidden items-center gap-2 text-xs font-bold sm:flex" to={`/site/${config.slug}/listings`}>{c.ctaText}<ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{config.listings.slice(0, 3).map((listing) => <LandCard key={listing.id} config={config} listing={listing} />)}</div></div></section></main><Footer config={config} /></div>;
}

export function LandPlotsListings({ config }: SiteTemplateProps) {
  const c = config.content;
  const [subtype, setSubtype] = useState("all");
  const subtypes = useMemo(() => Array.from(new Set(config.listings.filter((listing) => listing.property_category === "arsa").map((listing) => propertySubtypeFor(listing)).filter(Boolean))) as string[], [config.listings]);
  const filtered = subtype === "all" ? config.listings : config.listings.filter((listing) => propertySubtypeFor(listing) === subtype);
  const labelFor = (value: string) => propertyTaxonomyLabel(config, { ...config.listings.find((listing) => propertySubtypeFor(listing) === value)!, property_category: "arsa", property_subtype: value as Listing["property_subtype"] });
  return <div {...fineTuneAttributes(config)} style={landStyle(config)}><Header config={config} /><main><section className="bg-[var(--lp-primary)] px-5 py-20 text-white sm:px-8 lg:px-10"><div className="mx-auto max-w-[1400px]"><div className="text-xs font-bold uppercase tracking-[.2em] text-[var(--lp-accent)]">{c.eyebrow}</div><h1 className="mt-4 font-[family-name:var(--lp-heading)] text-6xl font-bold">{c.listingsTitle}</h1><p className="mt-4 max-w-2xl leading-7 text-white/65">{c.listingsDescription}</p></div></section><section className="mx-auto max-w-[1400px] px-5 py-14 sm:px-8 lg:px-10"><div className="flex flex-wrap gap-2"><button onClick={() => setSubtype("all")} className={`border px-4 py-2 text-xs font-bold ${subtype === "all" ? "border-[var(--lp-primary)] bg-[var(--lp-primary)] text-white" : "border-[var(--lp-line)]"}`}>{c.allLabel}</button>{subtypes.map((value) => <button key={value} onClick={() => setSubtype(value)} className={`border px-4 py-2 text-xs font-bold ${subtype === value ? "border-[var(--lp-primary)] bg-[var(--lp-primary)] text-white" : "border-[var(--lp-line)]"}`}>{labelFor(value).replace(`${c.landLabel} · `, "")}</button>)}</div>{filtered.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map((listing) => <LandCard key={listing.id} config={config} listing={listing} />)}</div> : <p className="mt-10 border border-[var(--lp-line)] p-8 text-sm opacity-60">{c.emptyListings}</p>}</section><ClosedListingsGroups config={config} renderListing={(listing) => <LandCard config={config} listing={listing} />}/></main><Footer config={config} /></div>;
}

export function LandPlotsDetail({ config }: SiteTemplateProps) {
  const c = config.content; const listing = config.listing; const [contactOpen, setContactOpen] = useState(false); if (!listing) return null;
  const info = [[c.priceRangeLabel, formatListingPrice(listing)], [c.areaLabel, `${listing.m2} m²`], [c.locationLabel, formatListingLocation(listing)], [c.usageLabel, propertyTaxonomyLabel(config, listing)]];
  return <div {...fineTuneAttributes(config)} style={landStyle(config)}><Header config={config} /><main><section className="mx-auto max-w-[1400px] px-5 py-10 sm:px-8 lg:px-10"><Link className="inline-flex items-center gap-2 text-xs font-bold" to={`/site/${config.slug}/listings`}><ArrowLeft className="h-4 w-4" />{c.backLabel}</Link><div className="relative mt-8"><img src={getListingImage(listing)} alt={listing.title} className="aspect-[16/8] w-full object-cover" /><span className="absolute right-5 top-5 bg-[var(--lp-primary)] px-4 py-2 text-xs font-bold text-white">{listing.listing_type === "sale" ? c.saleLabel : c.rentLabel}</span></div><div className="mt-9 grid gap-12 lg:grid-cols-[1fr_360px]"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-[var(--lp-accent)]">{formatListingLocation(listing)}</div><h1 className="mt-3 font-[family-name:var(--lp-heading)] text-5xl font-bold leading-tight">{listing.title}</h1><p className="mt-6 max-w-3xl leading-8 opacity-65">{listing.description}</p><div className="mt-10 grid gap-3 sm:grid-cols-2">{info.map(([label, value]) => <div key={label} className="border border-[var(--lp-line)] bg-[var(--lp-soft)] p-5"><div className="text-[10px] font-bold uppercase tracking-wider opacity-50">{label}</div><div className="mt-2 font-[family-name:var(--lp-heading)] text-2xl font-bold">{value}</div></div>)}</div><section className="mt-12 border-t border-[var(--lp-line)] pt-10"><h2 className="font-[family-name:var(--lp-heading)] text-4xl font-bold">{c.listingFeaturesLabel}</h2><div className="mt-7"><FeatureList listing={listing} /></div></section></div><aside className="h-fit border-t-4 border-[var(--lp-accent)] bg-[var(--lp-soft)] p-7 lg:sticky lg:top-6"><h2 className="font-[family-name:var(--lp-heading)] text-3xl font-bold">{c.tourTitle}</h2><p className="mt-3 text-sm leading-7 opacity-60">{c.tourDescription}</p><button data-site-button onClick={() => setContactOpen(true)} className="mt-6 w-full bg-[var(--site-button)] px-5 py-4 text-sm font-bold text-[var(--site-button-text)]">{c.contactActionLabel}</button></aside></div></section></main><Footer config={config} /><LeadDialog config={config} listing={listing} open={contactOpen} onClose={() => setContactOpen(false)} /></div>;
}
