import { FormEvent, useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Member = { user_id: string; role: "owner" | "editor" | "agent" | "viewer"; joined_at: string };
type Invitation = { id: string; email: string; role: string; accepted_at: string | null; canceled_at: string | null; expires_at: string };
const roles = ["editor", "agent", "viewer"] as const;

export function WorkspaceMembers({ workspaceId, authHeaders }: { workspaceId: string; authHeaders: Record<string, string> }) {
  const [members, setMembers] = useState<Member[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]);
  const [email, setEmail] = useState(""); const [role, setRole] = useState<(typeof roles)[number]>("viewer"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const request = useCallback(async (path: string, init?: RequestInit) => { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...authHeaders, ...init?.headers } }); if (!response.ok) throw new Error((await response.json()).error || "İşlem başarısız."); return response.status === 204 ? {} : response.json(); }, [authHeaders]);
  const load = useCallback(async () => { try { const [memberData, invitationData] = await Promise.all([request(`/api/workspaces/${workspaceId}/members`), request(`/api/workspaces/${workspaceId}/invitations`)]); setMembers(memberData.members || []); setInvitations(invitationData.invitations || []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ekip yüklenemedi."); } }, [request, workspaceId]);
  useEffect(() => { void load(); }, [load]);
  async function invite(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await request(`/api/workspaces/${workspaceId}/invitations`, { method: "POST", body: JSON.stringify({ email, role }) }); setEmail(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Davet gönderilemedi."); } finally { setBusy(false); } }
  const mutate = async (path: string, init: RequestInit) => { setBusy(true); setError(""); try { await request(path, init); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "İşlem başarısız."); } finally { setBusy(false); } };
  return <Card className="rounded-[2rem] border-[#173f32]/10 bg-[#fbfaf7]"><CardHeader><CardTitle>Workspace ekibi</CardTitle><CardDescription>Dashboard erişimi olan üyeleri ve bekleyen davetleri yönetin.</CardDescription></CardHeader><CardContent className="space-y-5">{error ? <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}<form onSubmit={invite} className="grid gap-3 sm:grid-cols-[1fr_140px_auto]"><div><Label htmlFor="workspace-invite-email">E-posta</Label><Input id="workspace-invite-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></div><div><Label htmlFor="workspace-invite-role">Rol</Label><select id="workspace-invite-role" value={role} onChange={(event) => setRole(event.target.value as typeof role)} className="mt-2 h-10 w-full rounded-md border bg-white px-3">{roles.map((item) => <option key={item}>{item}</option>)}</select></div><Button className="self-end" disabled={busy}>Davet et</Button></form><div className="space-y-2">{members.map((member) => <div key={member.user_id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border bg-white p-3"><code className="text-xs">{member.user_id}</code>{member.role === "owner" ? <strong className="text-sm">owner</strong> : <div className="flex gap-2"><select aria-label="Üye rolü" value={member.role} disabled={busy} onChange={(event) => void mutate(`/api/workspaces/${workspaceId}/members/${member.user_id}`, { method: "PATCH", body: JSON.stringify({ role: event.target.value }) })} className="rounded-md border px-2 text-sm">{roles.map((item) => <option key={item}>{item}</option>)}</select><Button size="sm" variant="outline" disabled={busy} onClick={() => void mutate(`/api/workspaces/${workspaceId}/members/${member.user_id}`, { method: "DELETE" })}>Çıkar</Button></div>}</div>)}</div>{invitations.filter((item) => !item.accepted_at && !item.canceled_at).map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-dashed p-3 text-sm"><span>{item.email} · {item.role}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={() => void mutate(`/api/workspaces/${workspaceId}/invitations/${item.id}/resend`, { method: "POST" })}>Yeniden gönder</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => void mutate(`/api/workspaces/${workspaceId}/invitations/${item.id}`, { method: "DELETE" })}>İptal</Button></div></div>)}</CardContent></Card>;
}
